DROP TABLE BOOK_PUBLISHER CASCADE CONSTRAINT;
DROP SEQUENCE PUBLISH_CODE;
DROP TABLE BOOK_GENRE CASCADE CONSTRAINT;
DROP TABLE BOOKINFO CASCADE CONSTRAINT;
DROP TABLE BOOK_STATUSCODE CASCADE CONSTRAINT;
DROP TABLE BOOK_STATUS CASCADE CONSTRAINT;
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE BOOK_CODE;
DROP TABLE BOOK_BORROW CASCADE CONSTRAINT;
DROP SEQUENCE BORROW_SEQ;
DROP TABLE BOOK_RESERVE CASCADE CONSTRAINT;
DROP SEQUENCE RESERVE_SEQ;

--출판사
CREATE TABLE BOOK_PUBLISHER(
	PUBLISH_CODE NUMBER PRIMARY KEY,
	PUBLISH_NAME VARCHAR2(100) NOT NULL
);
CREATE SEQUENCE PUBLISH_CODE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE BOOK_PUBLISHER IS '출판사';
COMMENT ON COLUMN BOOK_PUBLISHER.PUBLISH_CODE IS '출판사코드';
COMMENT ON COLUMN BOOK_PUBLISHER.PUBLISH_NAME IS '출판사이름';


--장르
CREATE TABLE BOOK_GENRE(
	GENRE_CODE NUMBER PRIMARY KEY,
	GENRE_NAME VARCHAR2(50) NOT NULL
);
COMMENT ON TABLE BOOK_GENRE IS '장르';
COMMENT ON COLUMN BOOK_GENRE.GENRE_CODE IS '장르코드';
COMMENT ON COLUMN BOOK_GENRE.GENRE_NAME IS '장르이름';

--도서상세정보
CREATE TABLE BOOKINFO(
	BOOK_CODE NUMBER,
	ISBN VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	AUTHOR VARCHAR2(100) NOT NULL,
	GENRE_CODE NUMBER NOT NULL,
	PUBLISH_CODE NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	PUBLISH_DATE DATE NOT NULL,
	THUMBNAIL CLOB,
	CONTENT CLOB,
	INTRO CLOB,
	REVIEW CLOB,
	AUTHORINFO CLOB
);
CREATE SEQUENCE BOOK_CODE START WITH 1 INCREMENT BY 1;
ALTER TABLE BOOKINFO  ADD CONSTRAINT BOOKINFO_PK PRIMARY KEY (BOOK_CODE);
ALTER TABLE BOOKINFO  ADD CONSTRAINT BOOKINFO_GENRE FOREIGN KEY (GENRE_CODE) REFERENCES BOOK_GENRE(GENRE_CODE);
ALTER TABLE BOOKINFO  ADD CONSTRAINT BOOKINFO_PUBLISH FOREIGN KEY (PUBLISH_CODE) REFERENCES BOOK_PUBLISHER(PUBLISH_CODE);

COMMENT ON TABLE BOOKINFO IS '도서상세정보';
COMMENT ON COLUMN BOOKINFO.BOOK_CODE IS '도서코드';
COMMENT ON COLUMN BOOKINFO.ISBN IS 'ISBN';
COMMENT ON COLUMN BOOKINFO.TITLE IS '도서명';
COMMENT ON COLUMN BOOKINFO.AUTHOR IS '저자';
COMMENT ON COLUMN BOOKINFO.GENRE_CODE IS '장르코드';
COMMENT ON COLUMN BOOKINFO.PUBLISH_CODE IS '출판사코드';
COMMENT ON COLUMN BOOKINFO.PRICE IS '가격';
COMMENT ON COLUMN BOOKINFO.PUBLISH_DATE IS '발행일';
COMMENT ON COLUMN BOOKINFO.THUMBNAIL IS '썸네일';
COMMENT ON COLUMN BOOKINFO.CONTENT IS '목차';
COMMENT ON COLUMN BOOKINFO.INTRO IS '도서소개';
COMMENT ON COLUMN BOOKINFO.REVIEW IS '서평';
COMMENT ON COLUMN BOOKINFO.AUTHORINFO IS '저자소개';

--
CREATE TABLE BOOK_STATUSCODE(
	STATUS_CODE CHAR(1) DEFAULT 'A' PRIMARY KEY,
	STATUS VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE BOOK_STATUSCODE IS '상태코드';
COMMENT ON COLUMN BOOK_STATUSCODE.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN BOOK_STATUSCODE.STATUS IS '상태이름';

--
CREATE TABLE BOOK_STATUS(
	BOOK_SEQ NUMBER PRIMARY KEY,
	STATUS_TITLE VARCHAR2(200) NOT NULL,
	STATUS_CODE CHAR(1) NOT NULL,
	BOOK_CODE NUMBER NOT NULL,
);
CREATE SEQUENCE BOOK_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE BOOK_STATUS  ADD CONSTRAINT BOOK_STATUS_PK PRIMARY KEY (BOOK_SEQ);
ALTER TABLE BOOK_STATUS  ADD CONSTRAINT STATUS_STATUSCOD FOREIGN KEY (STATUS_CODE) REFERENCES BOOK_STATUSCODE(STATUS_CODE);
ALTER TABLE BOOK_STATUS  ADD CONSTRAINT STATUS_BOOKCODE FOREIGN KEY (BOOK_CODE) REFERENCES BOOKINFO(BOOK_CODE);

COMMENT ON TABLE BOOK_STATUS IS '도서상태';
COMMENT ON COLUMN BOOK_STATUS.BOOK_SEQ IS '관리번호';
COMMENT ON COLUMN BOOK_STATUS.STATUS_TITLE IS '도서명';
COMMENT ON COLUMN BOOK_STATUS.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN BOOK_STATUS.BOOK_CODE IS '도서코드';


--
CREATE TABLE BOOK_BORROW(
	BORROW_SEQ NUMBER PRIMARY KEY,
	BORROW_TITLE VARCHAR2(200) NOT NULL,
	START_DATE DATE DEFAULT SYSDATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	RENEW CHAR(1) DEFAULT 'N' NOT NULL,
	BORROW_OK CHAR(1) DEFAULT 'N' NOT NULL,
	USER_ID NUMBER NOT NULL,
	BOOK_SEQ NUMBER NOT NULL);	
CREATE SEQUENCE BORROW_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE BOOK_BORROW ADD CONSTRAINT BORROW_BOOKSEQ FOREIGN KEY (BOOK_SEQ) REFERENCES BOOK_STATUS (BOOK_SEQ);
ALTER TABLE BOOK_BORROW ADD CONSTRAINT BORROW_USERID FOREIGN KEY (USER_ID) REFERENCES BOOK_USERINFO (USER_ID);

COMMENT ON TABLE BOOK_BORROW IS '대출';
COMMENT ON COLUMN BOOK_BORROW.BORROW_SEQ IS '대출SEQ';
COMMENT ON COLUMN BOOK_BORROW.BORROW_TITLE IS '도서명';
COMMENT ON COLUMN BOOK_BORROW.START_DATE IS '대여일';
COMMENT ON COLUMN BOOK_BORROW.RETURN_DATE IS '반납일';
COMMENT ON COLUMN BOOK_BORROW.RENEW IS '연장여부';
COMMENT ON COLUMN BOOK_BORROW.BORROW_OK IS '대출여부';
COMMENT ON COLUMN BOOK_BORROW.USER_ID IS '회원번호';
COMMENT ON COLUMN BOOK_BORROW.BOOK_SEQ IS '관리번호';


--
CREATE TABLE BOOK_RESERVE(
	RESERVE_SEQ NUMBER PRIMARY KEY,
	RESERVE_TITLE VARCHAR2(200) NOT NULL,
	RESERVE_DATE DATE NOT NULL,
	RESERVE_OK CHAR(1) DEFAULT 'N' NOT NULL,
	USER_ID NUMBER NOT NULL,
	BOOK_SEQ NUMBER NOT NULL
);
CREATE SEQUENCE RESERVE_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE BOOK_BORROW ADD CONSTRAINT BORROW_BOOKSEQ FOREIGN KEY (BOOK_SEQ) REFERENCES BOOK_STATUS (BOOK_SEQ);
ALTER TABLE BOOK_BORROW ADD CONSTRAINT BORROW_USERID FOREIGN KEY (USER_ID) REFERENCES BOOK_USERINFO (USER_ID);

COMMENT ON TABLE BOOK_RESERVE IS '예약';
COMMENT ON COLUMN BOOK_RESERVE.RESERVE_SEQ IS '예약SEQ';
COMMENT ON COLUMN BOOK_RESERVE.RESERVE_TITLE IS '도서명';
COMMENT ON COLUMN BOOK_RESERVE.RESERVE_DATE IS '예약시간';
COMMENT ON COLUMN BOOK_RESERVE.RESERVE_OK IS '예약여부';
COMMENT ON COLUMN BOOK_RESERVE.USER_ID IS '회원번호';
COMMENT ON COLUMN BOOK_RESERVE.BOOK_SEQ IS '관리번호';


--
CREATE TABLE ASK_BOARD(
	ASK_SEQ NUMBER PRIMARY KEY,
	ASK_TITLE VARCHAR2(100) NOT NULL,
	ASK_CONTENTS VARCHAR2(2000) NOT NULL,
	ASK_REGDATE DATE DEFAULT SYSDATE NOT NULL,
	USER_ID NUMBER NOT NULL
);
CREATE SEQUENCE ASK_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE ASK_BOARD ADD CONSTRAINT ASK_USERID FOREIGN KEY (USER_ID) REFERENCES BOOK_USERINFO (USER_ID);

COMMENT ON TABLE ASK_BOARD IS '문의게시판(회원)';
COMMENT ON COLUMN ASK_BOARD.ASK_SEQ IS '글번호';
COMMENT ON COLUMN ASK_BOARD.ASK_TITLE IS '제목';
COMMENT ON COLUMN ASK_BOARD.ASK_CONTENTS IS '내용';
COMMENT ON COLUMN ASK_BOARD.ASK_REGDATE IS '작성일';
COMMENT ON COLUMN ASK_BOARD.USER_ID IS '회원번호';

--
CREATE TABLE REPLY_BOARD(
	RE_SEQ NUMBER PRIMARY KEY,
	ASK_SEQ NUMBER NOT NULL,
	RE_TITLE VARCHAR2(100) NOT NULL,
	RE_CONTENTS VARCHAR2(2000) NOT NULL,
	RE_REGDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE RE_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE REPLY_BOARD ADD CONSTRAINT REPLY_FK FOREIGN KEY (ASK_SEQ) REFERENCES ASK_BOARD (ASK_SEQ);

COMMENT ON TABLE REPLY_BOARD IS '답글게시판(관리자)';
COMMENT ON COLUMN REPLY_BOARD.RE_SEQ IS '답글번호';
COMMENT ON COLUMN REPLY_BOARD.ASK_SEQ IS '글번호';
COMMENT ON COLUMN REPLY_BOARD.RE_TITLE IS '제목';
COMMENT ON COLUMN REPLY_BOARD.RE_CONTENTS IS '내용';
COMMENT ON COLUMN REPLY_BOARD.RE_REGDATE IS '작성일';

--
CREATE TABLE FILE_BOARD(
	FILEBOARD_SEQ NUMBER PRIMARY KEY, --FILE_SEQ 수정예정
	BOARD_SEQ NUMBER NOT NULL,
	ORIGIN_FNAME VARCHAR2(500) NOT NULL,
	STORED_FNAME VARCHAR2(1000) NOT NULL,
	FILE_REGDATE DATE DEFAULT SYSDATE NOT NULL,
	FILE_DELFLAG CHAR(1)  DEFAULT 'N'
);
CREATE SEQUENCE FILEBOARD_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE FILE_BOARD ADD CONSTRAINT FILE_FK FOREIGN KEY (BOARD_SEQ) REFERENCES ASK_BOARD (ASK_SEQ);


COMMENT ON TABLE FILE_BOARD IS '파일';
COMMENT ON COLUMN FILE_BOARD.FILEBOARD_SEQ IS '파일번호';
COMMENT ON COLUMN FILE_BOARD.BOARD_SEQ IS '글번호';
COMMENT ON COLUMN FILE_BOARD.ORIGIN_FNAME IS '파일이름';
COMMENT ON COLUMN FILE_BOARD.STORED_FNAME IS '저장이름';
COMMENT ON COLUMN FILE_BOARD.FILE_REGDATE IS '등록일';
COMMENT ON COLUMN FILE_BOARD.FILE_DELFLAG IS '삭제여부';

--
CREATE TABLE HOPE_BOARD(
	HO_SEQ NUMBER PRIMARY KEY,
	HO_TITLE VARCHAR2(200) NOT NULL,
	HO_AUTHOR VARCHAR2(100) NOT NULL,
	HO_PUBLISHER VARCHAR2(100) NOT NULL,
	HO_REGDATE DATE DEFAULT SYSDATE NOT NULL,
	USER_ID NUMBER NOT NULL
);
CREATE SEQUENCE HO_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE HOPE_BOARD ADD CONSTRAINT HOPE_USERID FOREIGN KEY (USER_ID) REFERENCES BOOK_USERINFO (USER_ID);

COMMENT ON TABLE HOPE_BOARD IS '희망도서신청';
COMMENT ON COLUMN HOPE_BOARD.HO_SEQ IS '신청번호';
COMMENT ON COLUMN HOPE_BOARD.HO_TITLE IS '도서명';
COMMENT ON COLUMN HOPE_BOARD.HO_AUTHOR IS '저자';
COMMENT ON COLUMN HOPE_BOARD.HO_PUBLISHER IS '출판사';
COMMENT ON COLUMN HOPE_BOARD.HO_REGDATE IS '작성일';
COMMENT ON COLUMN HOPE_BOARD.USER_ID IS '회원번호';

--
CREATE TABLE REHOPE_BOARD(
	RH_SEQ NUMBER PRIMARY KEY,
	HO_SEQ NUMBER NOT NULL,
	HO_STATUS CHAR(1) NOT NULL,
	REASON VARCHAR2(500)
);
CREATE SEQUENCE RH_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE REHOPE_BOARD ADD CONSTRAINT REHOPE_FK FOREIGN KEY (HO_SEQ) REFERENCES HOPE_BOARD (HO_SEQ);


COMMENT ON TABLE REHOPE_BOARD IS '희망도서답변';
COMMENT ON COLUMN REHOPE_BOARD.RH_SEQ IS '답글번호';
COMMENT ON COLUMN REHOPE_BOARD.HO_SEQ IS '신청번호';
COMMENT ON COLUMN REHOPE_BOARD.HO_STATUS IS '신청상태';
COMMENT ON COLUMN REHOPE_BOARD.REASON IS '거절사유';

--
CREATE TABLE NOTICE_BOARD(
	NO_SEQ NUMBER PRIMARY KEY,
	N0_TITLE VARCHAR2(50) NOT NULL,
	NO_CONTENTS VARCHAR2(3000) NOT NULL,
	NO_REGDATE DATE DEFAULT SYSDATE NOT NULL,
	NO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
	USER_ID NUMBER  NOT NULL
);
CREATE SEQUENCE NO_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE NOTICE_BOARD ADD CONSTRAINT NOTICE_USERID FOREIGN KEY (USER_ID) REFERENCES BOOK_USERINFO (USER_ID);

COMMENT ON TABLE NOTICE_BOARD IS '공지사항게시판';
COMMENT ON COLUMN NOTICE_BOARD.NO_SEQ IS '글번호';
COMMENT ON COLUMN NOTICE_BOARD.N0_TITLE IS '제목';
COMMENT ON COLUMN NOTICE_BOARD.NO_CONTENTS IS '내용';
COMMENT ON COLUMN NOTICE_BOARD.NO_REGDATE IS '작성일';
COMMENT ON COLUMN NOTICE_BOARD.NO_DELFLAG IS '삭제여부';
COMMENT ON COLUMN NOTICE_BOARD.USER_ID IS '회원번호';

--FILE TABLE 이름 그냥  FILE가능?
--파일 테이블 FK
--TITLE 이름 같아도 되는지?
--프로시저


